### ISSUE TITLE
Submitting to wp.org

### ISSUE THREAD

**Issue by ideag** [gingersoulrecords/WordPen#3]
Hi, for submitting to WP.org there are a couple of things you would be better at doing, than I would:

1. Short description (up to 150 characters, no formatting)
1. Long description - can include links, bullet lists, bold/italic, etc. At least a couple paragraphs. A good place to mention your other plugins, including premium ones.
1. Logo and cover images - we discussed those before and they will only be needed after plugin is confirmed, but it is always good to have them ready.

P.S. is gsr username on wordpress.org yours? it seems to be registered but never used really used. If it is, could you give me access to that account - I'll do your submissions using it.

**Comment by gingersoulrecords** [comment]
1. Embed pens from CodePen without the 'edit' frame. 

2. [CodePen](http://codepen.io/) is a 'playground for the front end web' where you can write and share HTML/CSS/JS demos, called pens. It's a fountain of inspiration for web designers and a useful resource for those learning to write - and marvel at - front end code.

WordPen is an effort to bring the best of CodePen to WordPress, with minimal code work. Simply paste a URL from CodePen, save your WordPen, and embed a shortcode in your layout.

HTML, CSS, and JS code will be editable, and all connected resources linked to the pen will be included with the shortcode.

Not all pens were designed to be featured with WordPen, so you may wish to start with background- and foreground-friendly pens, which are collected [here](http://codepen.io/gingersoulrecords/collections/public/).

**Comment by ideag** [comment]
Sumbited to the repo
